language: node_js
node_js:
- 4
- 5
- 6
- 7

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change

deploy:
  provider: npm
  email: hello@trailsjs.org
  api_key:
    secure: PuxyuCcyILXRWfABPP0Ay8bgM+29ctBGdvMMNjPtkLK25SVTS48jhEOJLBAsb0AxtjUM2QSt90NTjG+vm4YlGDWUFi92M1bbOgsdNgPO/rx1ZMEr1PDi5PhhcTR2ASSzyFYWtWyjGsBf9K8KFL6CLL2SUwbNS6wpW7GRrYcL+jTfe2wWbleMb0r6qEnBW9CXJLxdewqKBpyFBcUR2Y0jMytZwSqSNBYYpP/JnmXF7e5x1fv9Y9Kzn2Z8+bvJMaOzo8Swonf8iqXM3apRTT+h3Jk4wPA8zqpZ2jNed4l3rrNpgzqtScQE3ji41FzZHETC8J1R9xJtDYhTAjd2L03HPwyUJrj6WGWmJBXXebHKD4hfHGYQAVlGzNcSBB+4MC0zmF8seXdcjZMYRPp5gYIwjjbY9CZp0YtFbpqBTijv5LIT/ftmYB+paPglBoK13xsEK7QE0baHL8RHoSQyaUmsSNSG2DrHrqIZZjGSwOX2gRfXlRI4uXodeD45LoLCJihr+2xMvNIl6X/hbKC2COogAxgWttQPlce8o90frdcfBn06nLPTJzu4cwXmfNUtUrup4psat+PR6oensCG/K8R90yBDOIbi4dLQItiOiHJ0crBB87xcUyZnVnJSAQeX2wqT2PlYssIIdhlgFtPTZLPOyVLtXsxIc8ESNVEwDQPVSqw=
  skip_cleanup: true
  on:
    tags: true
    repo: trailsjs/trailpack-repl
    node: 6
